require_relative '../lib/ia/extensions'
require_relative '../lib/ia/passenger'
require_relative '../lib/ia/train'
require_relative '../lib/ia/selection'
require_relative '../lib/ia/crossover'
require_relative '../lib/ia/mutation'